### ISSUE TITLE
【提案】揃ったあとの文言変更

### ISSUE THREAD

**Issue by akine** [Goi666/god7#24]
正解不正解は違う気がするので
ドメインのGOD7（神7）に合っている方が適当か。
以下提案

揃ったとき
・GOD7
・ゴッセブン
・YOU GOD!

揃わなかったとき
・NON7
・ノンセブン
・ノンゴッド

みたいな

**Comment by eeeichan** [comment]
イメージこんな感じですかね
![image](https://user-images.githubusercontent.com/40140038/62520191-07e3f400-b868-11e9-954b-a2dc1734ee53.png)

**Comment by eeeichan** [comment]
http://imgur.com/0YNl24h.gif
